### ISSUE TITLE
classifiers are missing

### ISSUE THREAD

**Issue by ma-siddiqui** [KushajveerSingh/Unsupervised-Parking-Lot-Detection#1]
Hi,

Its seems some classified weights are missing. Please advise where I can get those files. For example while running the code I am facing errors:

Traceback (most recent call last):
  File "model.py", line 140, in <module>
    outs = model.predict(video_path=args.video_path, x='data/images/test.jpg') 
  File "model.py", line 91, in predict
    outs = do_inference(x, self.dir)
  File "../Unsupervised-Parking-Lot-Detection/training/inference.py", line 77, in do_inference
    occu_model = get_occu_model()
  File "..Unsupervised-Parking-Lot-Detection/training/occu_classifier.py", line 208, in get_occu_model
    model.load_state_dict(torch.load('training/occu_classifier.pth'))
  File "~/anaconda3/envs/linedetector_dev/lib/python3.7/site-packages/torch/serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'training/occu_classifier.pth'

Thanks,

**Comment by KushajveerSingh** [comment]
The models used in `inference.py` including `occu_classifier.pth`, `color_classifier`, `pos_classifier` are not included in the repo, as I thought there were task-dependent and there was not much use of my pretrained models.

But you can train your own models. I have made available the entire training process in the [training/notebooks](https://github.com/KushajveerSingh/Unsupervised-Parking-Lot-Detection/tree/master/training/notebooks) folder. You just have to run the notebooks from top to bottom with some minor changes.

Also, the data I used in for training these models, is available in the [data](https://github.com/KushajveerSingh/Unsupervised-Parking-Lot-Detection/tree/master/data) folder.

Apologies for missing on this issue.

**Comment by tatamagochi** [comment]
Stumbled upon the same issue. Managed to train pose and color by changing the code a bit to fastai2. But there is no info on occupancy training. What does it use as input? cropped images out of labels? There is no occupancy related code under notebooks

**Comment by Uttsavv** [comment]
There is still no occ_classifier.pth file i don't see how the notebooks will give that.
